#!/usr/bin/env sh

ELECTRON_OZONE_PLATFORM_HINT=auto
GDK_BACKEND=wayland,x11
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=qt6ct
XCURSOR_THEME=XCursor-Pro-Light
XCURSOR_SIZE=24
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
_JAVA_AWT_WM_NONREPARENTING=1

exec sway --unsupported-gpu
